name: Update Model Daily

on:
  schedule:
    - cron: "0 6 * * *"  # every day at 6 AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Update data and retrain model
        run: |
          python src/data_collector.py
          python src/feature_engineering.py
          python src/model_trainer.py
          python src/predictor.py

      - name: Commit and push results
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto update: new predictions"
          git push

